# Generated by Django 4.1.7 on 2023-04-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_cc', '0003_alter_post_cuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
